In [1]:
from cprior.cdist import ci_interval
from cprior.cdist import ci_interval_exact

In [2]:
import numpy as np

from scipy import stats

In [3]:
dist = stats.gamma(4, 10)

CI interval from MCMC

In [4]:
x = dist.rvs(size=int(1e6), random_state=42)

In [5]:
ci_interval(x=x, interval_length=0.9, method="ETI")

array([11.36321512, 17.75748775])

In [6]:
ci_interval(x=x, interval_length=0.9, method="HDI")

array([10.92933934, 16.94237247])

CI interval exact

In [7]:
ci_interval_exact(dist=dist, interval_length=0.9, method="ETI")

array([11.3663184 , 17.75365653])

In [8]:
bounds = [(0, np.inf), (0, np.inf)]
ci_interval_exact(dist=dist, interval_length=0.9, method="HDI", bounds=bounds)

array([10.93729501, 16.94611345])